version: "3.8"
services:
  #app:
  #  image: "horse-order-service"
  #  build:
  #    context: .
  #  container_name: app
  #  environment:
  #    DATABASE_HOST: ${DATABASE_HOST}
  #    DATABASE_USERNAME: ${DATABASE_USERNAME}
  #    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #  ports:
  #    - "13000:13000"
  #  restart: always
  #  depends_on:
  #    - db
  db:
    image: postgres:16-alpine
    restart: always
    init: true
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=horse-order-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: horse_order_postgres_data
